-- MySQL Script generated by MySQL Workbench
-- Fri Dec 30 11:04:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Theater
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Theater
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Theater` DEFAULT CHARACTER SET utf8 ;
USE `Theater` ;

-- -----------------------------------------------------
-- Table `Theater`.`Buffet_worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Theater`.`Buffet_worker` (
  `bff_id` SMALLINT UNSIGNED NOT NULL,
  `bff_name` VARCHAR(64) NOT NULL,
  `bff_salary` SMALLINT UNSIGNED NOT NULL,
  `bff_timetable` DATETIME NOT NULL,
  PRIMARY KEY (`bff_id`),
  UNIQUE INDEX `bff_id_UNIQUE` (`bff_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Theater`.`Ticket_cashier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Theater`.`Ticket_cashier` (
  `tcc_id` SMALLINT UNSIGNED NOT NULL,
  `tcc_name` VARCHAR(64) NOT NULL,
  `tcc_salary` SMALLINT UNSIGNED NOT NULL,
  `tcc_timetable` DATETIME NOT NULL,
  `bff_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`tcc_id`),
  UNIQUE INDEX `tcc_id_UNIQUE` (`tcc_id` ASC) VISIBLE,
  INDEX `coffee_break1` (`bff_id` ASC) VISIBLE,
  CONSTRAINT `coffee_break1`
    FOREIGN KEY (`bff_id`)
    REFERENCES `Theater`.`Buffet_worker` (`bff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Theater`.`Ticket_checker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Theater`.`Ticket_checker` (
  `tch_id` SMALLINT UNSIGNED NOT NULL,
  `tch_name` VARCHAR(64) NOT NULL,
  `tch_salary` SMALLINT UNSIGNED NOT NULL,
  `tch_timetable` DATETIME NOT NULL,
  `bff_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`tch_id`),
  UNIQUE INDEX `tch_id_UNIQUE` (`tch_id` ASC) VISIBLE,
  INDEX `coffee_break5` (`bff_id` ASC) VISIBLE,
  CONSTRAINT `coffee_break5`
    FOREIGN KEY (`bff_id`)
    REFERENCES `Theater`.`Buffet_worker` (`bff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Theater`.`Wardrobe_worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Theater`.`Wardrobe_worker` (
  `wrd_id` SMALLINT UNSIGNED NOT NULL,
  `wrd_name` VARCHAR(64) NOT NULL,
  `wrd_salary` SMALLINT UNSIGNED NOT NULL,
  `wrd_timetable` DATETIME NOT NULL,
  `bff_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`wrd_id`),
  INDEX `coffee_break3` (`bff_id` ASC) VISIBLE,
  CONSTRAINT `coffee_break3`
    FOREIGN KEY (`bff_id`)
    REFERENCES `Theater`.`Buffet_worker` (`bff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Theater`.`Visitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Theater`.`Visitor` (
  `vis_id` SMALLINT UNSIGNED NOT NULL,
  `vis_name` VARCHAR(64) NOT NULL,
  `vis_email` VARCHAR(64) NULL,
  `vis_login` VARCHAR(32) NULL,
  `vis_password` VARCHAR(10) NULL,
  `tick_id` SMALLINT UNSIGNED NOT NULL,
  `fd_name` VARCHAR(32) NULL,
  `tcc_id` SMALLINT UNSIGNED NOT NULL,
  `tch_id` SMALLINT UNSIGNED NOT NULL,
  `bff_id` SMALLINT UNSIGNED NOT NULL,
  `wrd_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`vis_id`),
  UNIQUE INDEX `vis_id_UNIQUE` (`vis_id` ASC) VISIBLE,
  UNIQUE INDEX `tick_id_UNIQUE` (`tick_id` ASC) VISIBLE,
  INDEX `buy` (`tcc_id` ASC) VISIBLE,
  INDEX `check` (`tch_id` ASC) VISIBLE,
  INDEX `buy_food` (`bff_id` ASC) INVISIBLE,
  INDEX `give_clothes` (`wrd_id` ASC) VISIBLE,
  CONSTRAINT `buy`
    FOREIGN KEY (`tcc_id`)
    REFERENCES `Theater`.`Ticket_cashier` (`tcc_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `check`
    FOREIGN KEY (`tch_id`)
    REFERENCES `Theater`.`Ticket_checker` (`tch_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `buy_food`
    FOREIGN KEY (`bff_id`)
    REFERENCES `Theater`.`Buffet_worker` (`bff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `give_clothes`
    FOREIGN KEY (`wrd_id`)
    REFERENCES `Theater`.`Wardrobe_worker` (`wrd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Theater`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Theater`.`Ticket` (
  `tick_id` SMALLINT UNSIGNED NOT NULL,
  `tick_cost` TINYINT UNSIGNED NOT NULL,
  `tick_sit` TINYINT UNSIGNED NOT NULL,
  `tick_data` DATETIME NOT NULL,
  `tick_play_name` TEXT(64) NOT NULL,
  `vis_id` SMALLINT UNSIGNED NOT NULL,
  `tcc_id` SMALLINT UNSIGNED NOT NULL,
  `tch_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`tick_id`),
  UNIQUE INDEX `tick_id_UNIQUE` (`tick_id` ASC) VISIBLE,
  INDEX `visitorHas` (`vis_id` ASC) VISIBLE,
  INDEX `cashierGives` (`tcc_id` ASC) VISIBLE,
  INDEX `takes_off` (`tch_id` ASC) VISIBLE,
  CONSTRAINT `visitorHas`
    FOREIGN KEY (`vis_id`)
    REFERENCES `Theater`.`Visitor` (`vis_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cashierGives`
    FOREIGN KEY (`tcc_id`)
    REFERENCES `Theater`.`Ticket_cashier` (`tcc_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `takes_off`
    FOREIGN KEY (`tch_id`)
    REFERENCES `Theater`.`Ticket_checker` (`tch_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Theater`.`Food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Theater`.`Food` (
  `fd_id` SMALLINT UNSIGNED NOT NULL,
  `fd_name` VARCHAR(32) NOT NULL,
  `fd_type` VARCHAR(32) NOT NULL,
  `fd_cost` TINYINT UNSIGNED NOT NULL,
  `fd_count` SMALLINT UNSIGNED NOT NULL,
  `vis_id` SMALLINT UNSIGNED NOT NULL,
  `bff_id` SMALLINT UNSIGNED NOT NULL,
  UNIQUE INDEX `fd_id_UNIQUE` (`fd_id` ASC) VISIBLE,
  PRIMARY KEY (`fd_name`),
  INDEX `visitorHas1` (`vis_id` ASC) VISIBLE,
  INDEX `workerGives` (`bff_id` ASC) VISIBLE,
  CONSTRAINT `visitorHas1`
    FOREIGN KEY (`vis_id`)
    REFERENCES `Theater`.`Visitor` (`vis_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `workerGives`
    FOREIGN KEY (`bff_id`)
    REFERENCES `Theater`.`Buffet_worker` (`bff_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Theater`.`Actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Theater`.`Actor` (
  `act_id` SMALLINT UNSIGNED NOT NULL,
  `act_name` VARCHAR(64) NOT NULL,
  `act_salary` SMALLINT UNSIGNED NOT NULL,
  `act_timetable` TIME NOT NULL,
  `act_play` VARCHAR(64) NOT NULL,
  `act_role` VARCHAR(32) NOT NULL,
  `bff_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`act_id`),
  UNIQUE INDEX `act_id_UNIQUE` (`act_id` ASC) VISIBLE,
  INDEX `coffee_break2` (`bff_id` ASC) VISIBLE,
  CONSTRAINT `coffee_break2`
    FOREIGN KEY (`bff_id`)
    REFERENCES `Theater`.`Buffet_worker` (`bff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Theater`.`Play`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Theater`.`Play` (
  `pl_id` SMALLINT UNSIGNED NOT NULL,
  `pl_name` VARCHAR(64) NOT NULL,
  `pl_author` VARCHAR(32) NOT NULL,
  `pl_timetable` DATETIME NOT NULL,
  `pl_roles` VARCHAR(128) NOT NULL,
  `act_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`pl_id`),
  UNIQUE INDEX `pl_id_UNIQUE` (`pl_id` ASC) VISIBLE,
  INDEX `toActor` (`act_id` ASC) VISIBLE,
  CONSTRAINT `toActor`
    FOREIGN KEY (`act_id`)
    REFERENCES `Theater`.`Actor` (`act_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Theater`.`Cleaner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Theater`.`Cleaner` (
  `cln_id` SMALLINT UNSIGNED NOT NULL,
  `cln_name` VARCHAR(64) NOT NULL,
  `cln_salary` SMALLINT UNSIGNED NOT NULL,
  `cln_timetable` DATETIME NOT NULL,
  `bff_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`cln_id`),
  UNIQUE INDEX `cln_id_UNIQUE` (`cln_id` ASC) VISIBLE,
  INDEX `coffee_break4` (`bff_id` ASC) VISIBLE,
  CONSTRAINT `coffee_break4`
    FOREIGN KEY (`bff_id`)
    REFERENCES `Theater`.`Buffet_worker` (`bff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
